_format_version: "3.0"
services:
  - name: story-service
    url: http://story-service:8000
    routes:
      - name: story
        paths:
          - /api/v1/stories
  - name: ai-service
    url: http://ai-service:8000
    routes:
      - name: ai
        paths:
          - /api/v1/ai
  - name: analysis-service
    url: http://analysis-service:8000
    routes:
      - name: analysis
        paths:
          - /api/v1/analysis
  - name: context-service
    url: http://context-service:8000
    routes:
      - name: context
        paths:
          - /api/v1/context
  - name: auth-service
    url: http://auth-service:8000
    routes:
      - name: auth
        paths:
          - /api/v1/auth
  - name: websocket-service
    url: http://websocket-service:8000
    routes:
      - name: websocket
        paths:
          - /ws
